spring:
    application:
        name: demo
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1111
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      enabled: true

logging:
        level:
            org:
                hibernate:
                    SQL: DEBUG
